In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
data = pd.read_csv("standardized_data_four - standardized_data_three.csv (1).csv")

FileNotFoundError: [Errno 2] No such file or directory: 'standardized_data_four - standardized_data_three.csv (1).csv'

In [ ]:
data

,Program_Name,Organization_Name,Description_of_Progam,Link,Type,Educationa_Level,Student_criteria,Field_of_Study,Skills_preferred,Location,Timezone,Mode_of_Participation,Program_Duration,Deadline,Tuition_or_Fees,Stipend,Keywords,Tags
0,Princeton Laboratory learning Program,Princeton University,Science Outreach was created in 2022 to facili...,https://scienceoutreach.princeton.edu/laborato...,1,1,NaN,STEM,Research,Princeton University,1,1,Early Jul - Late Jul ( ≈ 1 month(s)),3,0,0,"Internship, Research Program, Mentorship, Skil...","Stem, Research"
1,Princeton Summer Journalism Program,Princeton University,The Princeton Summer Journalism Program (PSJP)...,https://psjp.princeton.edu/about-program/program,1,1,NaN,Journalism,Interest in journalism,"Hybrid (Virtual in July, Princeton University)",1,3,Early Jul - Early Aug ( ≈ 1 month(s)),2,0,0,"Workshop, High School, Hybrid, Career Advancement",Journalism
2,Princeton University Preparatory Program,Princeton University,The Princeton University Preparatory Program (...,https://pupp.princeton.edu/about/,1,1,NaN,NaN,"Collaboration, Presentation, Listening, Debating",Princeton University,1,1,NaN,6,0,0,"High School, Inclusion, Diversity, In-Person",STEM
3,Princeton Plasma Physics Laboratory High Schoo...,Princeton Plasma Physics Laboratory (PPPL),The Princeton Plasma Physics Laboratory (PPPL)...,https://www.pppl.gov/high-school-summer-intern...,2,1,NaN,Physics,"Physics, Chemistry, Advanced mathematics, Engi...",Princeton University,1,1,Early Jun - Late Aug ( ≈ 3 month(s)),3,0,0,"Research Program, Internship, In-person, High ...",Physics
4,Program in Algorithmic and Combinatorial Think...,Princeton University,"Explores discrete mathematics, algorithmic pri...",https://algorithmicthinking.org/,1,1,NaN,Computer Science,Strong mathematical foundation is likely prefe...,Princeton University,1,1,Late Jun - Late Jul ( ≈ 1 month(s)),10,"1,850",0,"Workshop, Summer Camp,","STEM, Mathematics, Computer Science"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Commonwealth Honors Academy,Murray State University,A three-week academic enrichment program held ...,https://www.murraystate.edu/cha/,1,2,(Mohawk Students),Honors Courses,"Academic Excellence, Time Management","Murray, KY, USA",2,1,Jun (3 week(s)),0,250,0,"College Credit, Academic Enrichment",High School Enrichment Program
95,Saint Regis Mohawk Scholars Program,Roswell Park Comprehensive Cancer Center,A program aimed at supporting Mohawk students ...,https://www.roswellpark.org/research/departmen...,1,1,(students worldwide with strong academic achie...,Indigenous Health Research,"Research Skills, Health Equity Understanding","Buffalo, NY, USA",1,3,"MYHA(weekly), Summer Internship(3 weeks), Coll...",0,0,1,"Indigenous Health, Cancer Research",High School and College Internships
96,Research Mentorship Program,"University of California, Santa Barbara",The Research Mentorship Program is a competiti...,https://www.summer.ucsb.edu/programs/research-...,1,1,(Rising 12th graders from underrepresented gro...,Interdisciplinary Research,"Research Techniques, Networking","Santa Barbara, CA, USA",5,3,Mid Jun - Early Aug ( ≈ 2 month(s)),3,"4,975",0,"University Research, Summer Program",Research Experience
97,ESTEEM/SER-Quest Summer Program,"University of Maryland, College Park",The ESTEEM/SER-Quest Summer Program is a 4-wee...,https://eng.umd.edu/minorities/pre-college-pro...,1,1,(students with an interest in quantitative ski...,Engineering,"Research Skills, Communication Skills","College Park, MD, USA",1,1,Early Jul - Early Aug ( ≈ 4 week(s)),4,0,0,"Engineering Research, College Prep",Engineering Research
98,SPARC Program,"California State University, East Bay",SPARC is a Free program for talented high scho...,https://www.sparc.camp/,1,0,NaN,"Quantitative Skills, Cognitive Science","Programming, Analytical Skills","Hayward, CA, USA",5,1,Late Jul - Late Jul ( ≈ 2 week(s)),0,0,0,"Quantitative Skills, Personal Growth",Quantitative Skills

In [ ]:
data.dtypes

Program_Name             object
Organization_Name        object
Description_of_Progam    object
Link                     object
Type                      int64
Educationa_Level          int64
Student_criteria         object
Field_of_Study           object
Skills_preferred         object
Location                 object
Timezone                  int64
Mode_of_Participation     int64
Program_Duration         object
Deadline                  int64
Tuition_or_Fees          object
Stipend                   int64
Keywords                 object
Tags                     object
dtype: object

In [ ]:
data.fillna(0, inplace=True)

In [ ]:
data.dtypes

Program_Name             object
Organization_Name        object
Description_of_Progam    object
Link                     object
Type                      int64
Educationa_Level          int64
Student_criteria         object
Field_of_Study           object
Skills_preferred         object
Location                 object
Timezone                  int64
Mode_of_Participation     int64
Program_Duration         object
Deadline                  int64
Tuition_or_Fees          object
Stipend                   int64
Keywords                 object
Tags                     object
dtype: object

In [ ]:
data

,Program_Name,Organization_Name,Description_of_Progam,Link,Type,Educationa_Level,Student_criteria,Field_of_Study,Skills_preferred,Location,Timezone,Mode_of_Participation,Program_Duration,Deadline,Tuition_or_Fees,Stipend,Keywords,Tags
0,Princeton Laboratory learning Program,Princeton University,Science Outreach was created in 2022 to facili...,https://scienceoutreach.princeton.edu/laborato...,1,1,0,STEM,Research,Princeton University,1,1,Early Jul - Late Jul ( ≈ 1 month(s)),3,0,0,"Internship, Research Program, Mentorship, Skil...","Stem, Research"
1,Princeton Summer Journalism Program,Princeton University,The Princeton Summer Journalism Program (PSJP)...,https://psjp.princeton.edu/about-program/program,1,1,0,Journalism,Interest in journalism,"Hybrid (Virtual in July, Princeton University)",1,3,Early Jul - Early Aug ( ≈ 1 month(s)),2,0,0,"Workshop, High School, Hybrid, Career Advancement",Journalism
2,Princeton University Preparatory Program,Princeton University,The Princeton University Preparatory Program (...,https://pupp.princeton.edu/about/,1,1,0,0,"Collaboration, Presentation, Listening, Debating",Princeton University,1,1,0,6,0,0,"High School, Inclusion, Diversity, In-Person",STEM
3,Princeton Plasma Physics Laboratory High Schoo...,Princeton Plasma Physics Laboratory (PPPL),The Princeton Plasma Physics Laboratory (PPPL)...,https://www.pppl.gov/high-school-summer-intern...,2,1,0,Physics,"Physics, Chemistry, Advanced mathematics, Engi...",Princeton University,1,1,Early Jun - Late Aug ( ≈ 3 month(s)),3,0,0,"Research Program, Internship, In-person, High ...",Physics
4,Program in Algorithmic and Combinatorial Think...,Princeton University,"Explores discrete mathematics, algorithmic pri...",https://algorithmicthinking.org/,1,1,0,Computer Science,Strong mathematical foundation is likely prefe...,Princeton University,1,1,Late Jun - Late Jul ( ≈ 1 month(s)),10,"1,850",0,"Workshop, Summer Camp,","STEM, Mathematics, Computer Science"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Commonwealth Honors Academy,Murray State University,A three-week academic enrichment program held ...,https://www.murraystate.edu/cha/,1,2,(Mohawk Students),Honors Courses,"Academic Excellence, Time Management","Murray, KY, USA",2,1,Jun (3 week(s)),0,250,0,"College Credit, Academic Enrichment",High School Enrichment Program
95,Saint Regis Mohawk Scholars Program,Roswell Park Comprehensive Cancer Center,A program aimed at supporting Mohawk students ...,https://www.roswellpark.org/research/departmen...,1,1,(students worldwide with strong academic achie...,Indigenous Health Research,"Research Skills, Health Equity Understanding","Buffalo, NY, USA",1,3,"MYHA(weekly), Summer Internship(3 weeks), Coll...",0,0,1,"Indigenous Health, Cancer Research",High School and College Internships
96,Research Mentorship Program,"University of California, Santa Barbara",The Research Mentorship Program is a competiti...,https://www.summer.ucsb.edu/programs/research-...,1,1,(Rising 12th graders from underrepresented gro...,Interdisciplinary Research,"Research Techniques, Networking","Santa Barbara, CA, USA",5,3,Mid Jun - Early Aug ( ≈ 2 month(s)),3,"4,975",0,"University Research, Summer Program",Research Experience
97,ESTEEM/SER-Quest Summer Program,"University of Maryland, College Park",The ESTEEM/SER-Quest Summer Program is a 4-wee...,https://eng.umd.edu/minorities/pre-college-pro...,1,1,(students with an interest in quantitative ski...,Engineering,"Research Skills, Communication Skills","College Park, MD, USA",1,1,Early Jul - Early Aug ( ≈ 4 week(s)),4,0,0,"Engineering Research, College Prep",Engineering Research
98,SPARC Program,"California State University, East Bay",SPARC is a Free program for talented high scho...,https://www.sparc.camp/,1,0,0,"Quantitative Skills, Cognitive Science","Programming, Analytical Skills","Hayward, CA, USA",5,1,Late Jul - Late Jul ( ≈ 2 week(s)),0,0,0,"Quantitative Skills, Personal Growth",Quantitative Skills

In [ ]:
data.isna()

,Program_Name,Organization_Name,Description_of_Progam,Link,Type,Educationa_Level,Student_criteria,Field_of_Study,Skills_preferred,Location,Timezone,Mode_of_Participation,Program_Duration,Deadline,Tuition_or_Fees,Stipend,Keywords,Tags
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
encoder = OneHotEncoder()

In [ ]:
data.dtypes

Program_Name             object
Organization_Name        object
Description_of_Progam    object
Link                     object
Type                      int64
Educationa_Level          int64
Student_criteria         object
Field_of_Study           object
Skills_preferred         object
Location                 object
Timezone                  int64
Mode_of_Participation     int64
Program_Duration         object
Deadline                  int64
Tuition_or_Fees          object
Stipend                   int64
Keywords                 object
Tags                     object
dtype: object

In [ ]:
transformer = ColumnTransformer(
    transformers=[
        ("oneHotEncoder", encoder, ['Program_Name', 'Organization_Name', 'Description_of_Program',
                                      'Link', 'Type', 'Educationa_Level', 'Student_criteria', 'Field_of_Study', 'Skills_preferred', 'Location', 'Timezone', 'Mode_of_Participation', 'Program_Duration', 'Deadline', 'Tuition_or_Fees', 'Stipend', 'Keywords', 'Tags']),
    ],
    remainder="passthrough"
)

In [ ]:
data.columns = data.columns.str.strip()

In [ ]:
print(data.columns.tolist())

['Program_Name', 'Organization_Name', 'Description_of_Progam', 'Link', 'Type', 'Educationa_Level', 'Student_criteria', 'Field_of_Study', 'Skills_preferred', 'Location', 'Timezone', 'Mode_of_Participation', 'Program_Duration', 'Deadline', 'Tuition_or_Fees', 'Stipend', 'Keywords', 'Tags']

In [ ]:
X_transformed = transformer.fit_transform(data)

ValueError: A given column is not a column of the dataframe